# Set this to true to get extra console output.
# Not necessary for most servers unless there is a bug.
# Default: false
debug-mode: false

# Setting this to true will allow players to shift+right-click shulker boxes inside inventories to open them.
# NOT RECOMMENDED: May cause issues with other plugins or duplications
# This option will only work with shulker boxes that already contain items.
# If the shulker box is empty, it will not work.
# Default: false
allow-inventory-right-click: false

# Only enable Shulker Box in regions where a player can't place a block.
# Requires WorldGuard. Doesn't apply to shulker boxes inside of inventories.
# Default: false
world-guard-mode: false

# Sound for opening shulker boxes.
open-sound:
  sound: "minecraft:block.shulker_box.open"
  category: "ui"
  volume: 1.0
  pitch: 1.0

# Sound for closing shulker boxes.
close-sound:
  sound: "minecraft:block.shulker_box.close"
  category: "ui"
  volume: 1.0
  pitch: 1.0

shop-menu:
  # Set this to true to enable the ShulkerPackX shop menu.
  # Default: true
  enabled: true

  # Set this to the default price for unknown materials.
  # Mojang may add more shulker box types in the future.
  default-price: 5.0
  
  # Change the prices for each shulker box here.
  price:
    SHULKER_BOX: 1.0
    WHITE_SHULKER_BOX: 5.0
    ORANGE_SHULKER_BOX: 5.0
    MAGENTA_SHULKER_BOX: 5.0
    LIGHT_BLUE_SHULKER_BOX: 5.0
    YELLOW_SHULKER_BOX: 5.0
    LIME_SHULKER_BOX: 5.0
    PINK_SHULKER_BOX: 5.0
    GRAY_SHULKER_BOX: 5.0
    LIGHT_GRAY_SHULKER_BOX: 5.0
    CYAN_SHULKER_BOX: 5.0
    PURPLE_SHULKER_BOX: 5.0
    BLUE_SHULKER_BOX: 5.0
    BROWN_SHULKER_BOX: 5.0
    GREEN_SHULKER_BOX: 5.0
    RED_SHULKER_BOX: 5.0
    BLACK_SHULKER_BOX: 5.0
