# Set this to true to get extra console output.
# Not necessary for most servers unless there is a bug.
# Default: false
debug-mode: false

# Setting this to true will allow players to shift+right-click shulker boxes inside of GUIs to open them.
# NOT RECOMMENDED: May cause issues with other plugins or duplications
# This option will only work with shulker boxes that already contain items.
# If the shulker box is empty, it will not work.
# Default: false
allow-inventory-right-click: false

shop-menu:
  # Set this to true to enable the ShulkerPackX shop menu.
  # Default: true
  enabled: true

  # Set this to the default price for unknown materials.
  # Mojang may add more shulker box types in the future.
  default-price: 5.0
  
  # Change the prices for each shulker box here.
  price:
    SHULKER_BOX: 1.0
    WHITE_SHULKER_BOX: 5.0
    ORANGE_SHULKER_BOX: 5.0
    MAGENTA_SHULKER_BOX: 5.0
    LIGHT_BLUE_SHULKER_BOX: 5.0
    YELLOW_SHULKER_BOX: 5.0
    LIME_SHULKER_BOX: 5.0
    PINK_SHULKER_BOX: 5.0
    GRAY_SHULKER_BOX: 5.0
    LIGHT_GRAY_SHULKER_BOX: 5.0
    CYAN_SHULKER_BOX: 5.0
    PURPLE_SHULKER_BOX: 5.0
    BLUE_SHULKER_BOX: 5.0
    BROWN_SHULKER_BOX: 5.0
    GREEN_SHULKER_BOX: 5.0
    RED_SHULKER_BOX: 5.0
    BLACK_SHULKER_BOX: 5.0
